export const ADD_PAGE = {
  REQUEST: "ADD_PAGE_REQUEST",
  SUCCESS: "ADD_PAGE_SUCCESS",
  FAIL: "ADD_PAGE_FAIL",
  RESET: "ADD_PAGE_RESET",
};

export const ALL_PAGES = {
  REQUEST: "ALL_PAGES_REQUEST",
  SUCCESS: "ALL_PAGES_SUCCESS",
  FAIL: "ALL_PAGES_FAIL",
};

export const DELETE_PAGE = {
  REQUEST: "DELETE_PAGE_REQUEST",
  SUCCESS: "DELETE_PAGE_SUCCESS",
  FAIL: "DELETE_PAGE_FAIL",
  RESET: "DELETE_PAGE_RESET",
};

export const PAGE_DETAIL = {
  REQUEST: "PAGE_DETAIL_REQUEST",
  SUCCESS: "PAGE_DETAIL_SUCCESS",
  FAIL: "PAGE_DETAIL_FAIL",
  RESET: "PAGE_DETAIL_RESET",
};

export const UPDATE_PAGE = {
  REQUEST: "UPDATE_PAGE_REQUEST",
  SUCCESS: "UPDATE_PAGE_SUCCESS",
  FAIL: "UPDATE_PAGE_FAIL",
  RESET: "UPDATE_PAGE_RESET",
};
