export const ADD_BLOG = {
  REQUEST: "ADD_BLOG_REQUEST",
  SUCCESS: "ADD_BLOG_SUCCESS",
  FAIL: "ADD_BLOG_FAIL",
  RESET: "ADD_BLOG_RESET",
};

export const ALL_BLOGS = {
  REQUEST: "ALL_BLOGS_REQUEST",
  SUCCESS: "ALL_BLOGS_SUCCESS",
  FAIL: "ALL_BLOGS_FAIL"
};

export const DELETE_BLOG = {
  REQUEST: "DELETE_BLOG_REQUEST",
  SUCCESS: "DELETE_BLOG_SUCCESS",
  FAIL: "DELETE_BLOG_FAIL",
  RESET: "DELETE_BLOG_RESET",
};

export const BLOG_DETAIL = {
  REQUEST: "BLOG_DETAIL_REQUEST",
  SUCCESS: "BLOG_DETAIL_SUCCESS",
  FAIL: "BLOG_DETAIL_FAIL",
  RESET: "BLOG_DETAIL_RESET",
};

export const UPDATE_BLOG = {
  REQUEST: "UPDATE_BLOG_REQUEST",
  SUCCESS: "UPDATE_BLOG_SUCCESS",
  FAIL: "UPDATE_BLOG_FAIL",
  RESET: "UPDATE_BLOG_RESET",
};
